---

namespace: idiv_biodiversity
name: ssh
version: 0.2.0
readme: README.md
authors:
  - Christian Krause <christian.krause@idiv.de>
description: install and configure SSH
license_file: LICENSE
tags:
  - linux
  - openssh
  - ssh
  - sshd
dependencies: { }
repository: https://github.com/idiv-biodiversity/ansible-collection-ssh
documentation: https://github.com/idiv-biodiversity/ansible-collection-ssh
homepage: https://github.com/idiv-biodiversity/ansible-collection-ssh
issues: https://github.com/idiv-biodiversity/ansible-collection-ssh/issues
build_ignore:
  - .github
  - roles/*/molecule

...
