---

dependencies:

  - role: idiv_biodiversity.ssh.ssh
    tags:
      - ssh

galaxy_info:
  role_name: ssh_audited
  namespace: idiv_biodiversity

  author: Christian Krause
  description: 'configure OpenSSH based on latest ssh-audit recommendations'
  company: German Centre for Integrative Biodiversity Research (iDiv)
  license: MIT
  min_ansible_version: '2.9'

  platforms:

    - name: ArchLinux
      versions:
        - all

    - name: Debian
      versions:
        - bookworm
        - trixie

    - name: EL
      versions:
        - '9'
        - '10'

    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute

  galaxy_tags:
    - ssh

...
