---

__ssh_audit_install_tasks:
  files: >-
    {{
      __ssh_base_first_found |
        map('regex_replace', '^', 'install_') |
        map('regex_replace', '$', '.yml') |
        list
    }}
  paths:
    - tasks

__ssh_audit_break_system_packages_variants:
  default: no
  debian: yes
  ubuntu_24: yes
  ubuntu_26: yes

__ssh_audit_break_system_packages: >-
  {{
    __ssh_audit_break_system_packages_variants[__ssh_base_distro_version] |
      default(__ssh_audit_break_system_packages_variants[__ssh_base_distro]) |
      default(__ssh_audit_break_system_packages_variants['default'])
  }}

...
