---

provisioner:
  playbooks:
    converge: ../default/converge.yml
  inventory:
    group_vars:
      all:
        ssh_ciphers:
          - aes256-gcm@openssh.com
          - aes256-ctr
        ssh_macs:
          - hmac-sha2-512-etm@openssh.com
        ssh_modulus_min: 3071
      redhat:
        ssh_opt_out_crypto_policies: yes
        ssh_subsystems:
          - name: sftp
            command: '/usr/libexec/openssh/sftp-server -f AUTHPRIV -l INFO'
      ubuntu:
        ssh_subsystems:
          - name: sftp
            command: '/usr/lib/openssh/sftp-server -f AUTHPRIV -l INFO'
    host_vars:
      archlinux:
        ssh_subsystems:
          - name: sftp
            command: '/usr/lib/ssh/sftp-server -f AUTHPRIV -l INFO'

...
