---

- name: install python3-pip
  ansible.builtin.package:
    name: python3-pip

- name: install ssh-audit
  ansible.builtin.pip:
    name: ssh-audit
    break_system_packages: '{{ __ssh_audit_break_system_packages }}'
  register: __ssh_audit_pip_install

- name: show install ssh-audit
  ansible.builtin.debug:
    var: __ssh_audit_pip_install

...
