---

# -----------------------------------------------------------------------------
# first found snippets
# -----------------------------------------------------------------------------

__ssh_vars_files:
  files: >-
    {{ __ssh_base_first_found | map('regex_replace', '$', '.yml') | list }}
  paths:
    - vars

__ssh_sshd_config_templates:
  files: >-
    {{
      __ssh_base_first_found |
        map('regex_replace', '^', 'sshd_config_') |
        map('regex_replace', '$', '.conf') |
        list
    }}
  paths:
    - templates

__ssh_sshd_config_d_templates:
  files: >-
    {{
      __ssh_base_first_found |
        map('regex_replace', '^', 'sshd_config_d_') |
        map('regex_replace', '$', '.conf') |
        list
    }}
  paths:
    - templates

# -----------------------------------------------------------------------------
# defaults
# -----------------------------------------------------------------------------

__ssh_etc_sshd_config_mode_variants:
  default: '0644'
  redhat: '0600'

__ssh_etc_sshd_config_mode: >-
  {{
    __ssh_etc_sshd_config_mode_variants[__ssh_base_os] |
      default(__ssh_etc_sshd_config_mode_variants['default'])
  }}

__ssh_package_variants:
  default:
    - openssh-server
  archlinux:
    - openssh

__ssh_packages: >-
  {{
    __ssh_package_variants[__ssh_base_os] |
      default(__ssh_package_variants['default'])
  }}

__ssh_sshd_service_variants:
  default: sshd
  debian: ssh
  ubuntu_24: ssh

__ssh_sshd_service: >-
  {{
    __ssh_sshd_service_variants[__ssh_base_distro_version] |
      default(__ssh_sshd_service_variants[__ssh_base_distro]) |
      default(__ssh_sshd_service_variants['default'])
  }}

__ssh_genkeys_variants:
  default: ''
  archlinux: sshdgenkeys.service
  redhat: sshd-keygen.target

__ssh_genkeys: >-
  {{
    __ssh_genkeys_variants[__ssh_base_os] |
      default(__ssh_genkeys_variants['default'])
  }}

__ssh_sftp_server_locations:
  archlinux: /usr/lib/ssh/sftp-server
  debian: /usr/lib/openssh/sftp-server
  redhat: /usr/libexec/openssh/sftp-server

__ssh_sftp_server_location: >-
  {{
    __ssh_sftp_server_locations[__ssh_base_os]
  }}

...
